language: php
matrix:
  include:
  - php: 5.6
  - php: 7
    env:
    - EXECUTE_CS_CHECK=true
  - php: 7.1
  - php: hhvm
  - php: nightly
  allow_failures:
  - php: hhvm
  - php: nightly

before_install:
  - composer self-update
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer require --dev --no-update friendsofphp/php-cs-fixer ; fi
install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs
script:
  - ./vendor/bin/phpunit -c phpunit.travis.xml;
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi
